### ISSUE TITLE
Have you heard about Boss?

### ISSUE THREAD

**Issue by alefragnani** [The-Delphi-Project/PackageManagerRFC#21]
Hi,

Last year, during [Embarcadero Conference](https://embarcaderoconference.com.br/) event in Brazil, I've met a few people from the brazilian team, and they showed me a Dependency Manager project which they were working on. The project is open source and available in GitHub. It's called [Boss](https://github.com/hashload/boss). 

If I remember correctly, it already solves some of the issues that you pointed, like:
* not being tied to GitHub account (it also supports private repos)
* allows different versions of the same package

I'm not sure, but once being developed by the Embarcadero team, it _could be_ promoted by Embarcadero as well, receiving more attention than Delphinus received. Maybe, instead of _another_ package manager, why not combine the efforts?

Hope this helps

**Comment by vincentparrett** [comment]
I hadn't seen it, but whilst it's interesting, I have to question why it's not written in Delphi? It does look to be tied to git, in that to install a package you point it at a git repository and it looks for a boss.json file. 

I haven't had the time to work on this project for a while, and haven't been snowed under with offers of help so not sure when I will get something out.

**Comment by alefragnani** [comment]
I don’t remember the reason why they decided to use Go (maybe available libraries). About being tied to Git, I think it would be easy to support other SCM, if needed.

I share the feelings about lack of offers to help on open source projects. That’s why I thought about combined efforts with a project that appeared to share similar features. Sorry if that’s not the case.
